export const FETCH_QUIZZEZ_START = 'FETCH_QUIZZEZ_START'
export const FETCH_QUIZZEZ_SUCCESS = 'FETCH_QUIZZEZ_SUCCESS'
export const FETCH_QUIZZEZ_ERROR = 'FETCH_QUIZZEZ_ERROR'
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS'

export const ADD_ANSWER_TO_STATE = 'ADD_ANSWER_TO_STATE'
export const QUIZ_FINISHED = 'QUIZ_FINISHED'
export const NEXT_QUIZ_QUESTION = 'NEXT_QUIZ_QUESTION'
export const WRONG_QUIZ_ANSWER = 'WRONG_QUIZ_ANSWER'
export const RETRY_QUIZ = 'RETRY_QUIZ'

export const CREATE_QUIZ_QUESTION = 'CREATE_QUIZ_QUESTION'
export const RESET_QUIZ_PARAMETERS = 'RESET_QUIZ_PARAMETERS'

export const AUTH_SUCCESS = 'AUTH_SUCCESS'

export const AUTH_LOGOUT = 'AUTH_LOGOUT'